# Generated by Django 5.0.1 on 2024-01-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('sn', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OK', 'Good'), ('AVERIA', 'Not Good'), ('ROTO', 'Broke'), ('REPARANDO', 'Reparando')], max_length=10)),
            ],
        ),
    ]
