# Generated by Django 5.0.1 on 2024-01-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('POR', 'Portatil'), ('OSM', 'Ordenador de Sobremesa'), ('PAN', 'Pantalla'), ('RAT', 'Ratón')], max_length=200),
        ),
    ]
